In [1]:
import numpy as np

In [2]:
randmatrix=np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15],
                    [16,17,18,19,20],
                    [21,22,23,24,25]
                    ])

In [3]:
print("Shape = ",randmatrix.shape)
print("Mean=",randmatrix.mean())
print("Maximum = ",randmatrix.max())
print("Minimum = ",randmatrix.min())

Shape =  (5, 5)
Mean= 13.0
Maximum =  25
Minimum =  1


Exercise #2

In [4]:
A=np.array([20,12,5,39])
B=np.array([30,67,8,1])


In [5]:
A+B

array([50, 79, 13, 40])

In [6]:
A-B

array([-10, -55,  -3,  38])

In [7]:
A*B

array([600, 804,  40,  39])

In [8]:
A/B

array([ 0.66666667,  0.17910448,  0.625     , 39.        ])

Exercise 3


In [9]:
randq=np.random.randint(0,101,(6,6))

In [36]:
print(randq)
print(randq[0])
print(randq[:,5])
print(randq[2:4,2:4])
print(randq.sum())

[[ 71  64   4  23  35  22]
 [ 65  64   9  88  60   0]
 [ 76  84  60   2  78 100]
 [ 49  50  12  53  51   1]
 [ 96  37  45  14  67  48]
 [ 23  92  47  93  89  71]]
[71 64  4 23 35 22]
[ 22   0 100   1  48  71]
[[60  2]
 [12 53]]
1843


Exercise #4


In [43]:
img=np.random.randint(0,255,(5,5))
print(img)
print()
bright_img=np.clip(img+30,0,255)
print(bright_img)
print()
normalized_img=bright_img/255
print(normalized_img)

[[146 233 197  60 107]
 [234 202 236  26   2]
 [219 240 210 159 217]
 [ 55 205 254  93  29]
 [205 127 216 147 124]]

[[176 255 227  90 137]
 [255 232 255  56  32]
 [249 255 240 189 247]
 [ 85 235 255 123  59]
 [235 157 246 177 154]]

[[0.69019608 1.         0.89019608 0.35294118 0.5372549 ]
 [1.         0.90980392 1.         0.21960784 0.1254902 ]
 [0.97647059 1.         0.94117647 0.74117647 0.96862745]
 [0.33333333 0.92156863 1.         0.48235294 0.23137255]
 [0.92156863 0.61568627 0.96470588 0.69411765 0.60392157]]
