In [4]:
import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]


In [5]:
print(type(numbers))

<class 'numpy.ndarray'>


In [6]:
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(matrix.shape)

(3, 3)


In [8]:
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.17459495 0.26493458 0.51795605]
 [0.24990419 0.13080807 0.06710844]
 [0.4248686  0.42434928 0.27594515]]


In [11]:
A=np.array([1,2,3])
B=np.array([4,5,6])

In [12]:
print(A+B)

[5 7 9]


In [13]:
print(A-B)

[-3 -3 -3]


In [14]:
print(A*B)

[ 4 10 18]


In [15]:
print(A/B)

[0.25 0.4  0.5 ]


In [16]:
print(A*10)

[10 20 30]


In [17]:
marks=np.array([59,78,90,60,86])
print("mean=",marks.mean())
print("max=",marks.max())
print("min=",marks.min())
print("sum=",marks.sum())


mean= 74.6
max= 90
min= 59
sum= 373


In [18]:
matrix=matrix*10

In [19]:
#print(matrix[0,0])
#print(matrix[1])
print(matrix[:,2])

[30 60 90]


In [20]:
image=np.random.randint(0,256,(5,5))
print(image)

[[147  37 172 145 165]
 [202   2 197 127 169]
 [220  77 159 241 134]
 [152  65 205 119  17]
 [238  92  69  56   0]]


In [22]:
bright_image=np.clip(image+30,0,255)                                                                                                                                                                                                                                                                          #bright_image=image+30
print(bright_image)

[[177  67 202 175 195]
 [232  32 227 157 199]
 [250 107 189 255 164]
 [182  95 235 149  47]
 [255 122  99  86  30]]


In [24]:
normalized=image/255
print(normalized)

[[0.57647059 0.14509804 0.6745098  0.56862745 0.64705882]
 [0.79215686 0.00784314 0.77254902 0.49803922 0.6627451 ]
 [0.8627451  0.30196078 0.62352941 0.94509804 0.5254902 ]
 [0.59607843 0.25490196 0.80392157 0.46666667 0.06666667]
 [0.93333333 0.36078431 0.27058824 0.21960784 0.        ]]
